apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Edge-01: Dashboard + Projections + 13 Homes

resources:
  - ../../base/cortex-iq-dashboard    # Includes PostgreSQL
  - ../../base/cortex-iq-projections  # CQRS write-side (needs postgres)
  - ../../base/cortex-iq-homes

patches:
  - target:
      kind: Deployment
      name: cortex-iq-homes
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "13"
