apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: macula-platform

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - create-realm-job.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: macula-platform
