#  PowerDNS Authoritative Server Configuration

# PostgreSQL Backend
launch=gpgsql
gpgsql-host=postgres
gpgsql-port=5432
gpgsql-dbname=powerdns
gpgsql-user=powerdns
gpgsql-password=I0tfdqiuSbIs9iSwPdm4vNdiccfHKFKO
gpgsql-dnssec=yes

# Bind to all interfaces
local-address=0.0.0.0,::
local-port=53

# API and Webserver
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0,::/0
api=yes
api-key=SPUnDmhuBFnNgKYizc94HbMVdFpCs9st

# Logging
loglevel=5
log-dns-queries=yes
log-dns-details=yes

# Include additional configs (but we don't need them now)
# include-dir=/etc/powerdns/pdns.d
