# Override default gsqlite3 backend with gpgsql
launch=gpgsql
gpgsql-host=postgres
gpgsql-port=5432
gpgsql-dbname=powerdns
gpgsql-user=powerdns
gpgsql-password=I0tfdqiuSbIs9iSwPdm4vNdiccfHKFKO
gpgsql-dnssec=yes

# API and Webserver
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0,::/0
api=yes
api-key=SPUnDmhuBFnNgKYizc94HbMVdFpCs9st
