     STDIN
   1 launch=gpgsql
   2 gpgsql-host=postgres
   3 gpgsql-port=5432
   4 gpgsql-dbname=powerdns
   5 gpgsql-user=powerdns
   6 gpgsql-password=I0tfdqiuSbIs9iSwPdm4vNdiccfHKFKO
   7 webserver=yes
   8 webserver-port=8081
   9 api=yes
  10 api-key=SPUnDmhuBFnNgKYizc94HbMVdFpCs9st
