apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-iq-utilities
  namespace: macula-apps
  labels:
    app: cortex-iq-utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-iq-utilities
  template:
    metadata:
      labels:
        app: cortex-iq-utilities
    spec:
      containers:
      - name: utilities
        image: registry.macula.local:5000/macula/cortex-iq-utilities:latest
        imagePullPolicy: Always
        env:
        - name: BONDY_URL
          valueFrom:
            configMapKeyRef:
              name: bondy-client-config
              key: BONDY_URL
        - name: BONDY_REALM
          valueFrom:
            configMapKeyRef:
              name: bondy-client-config
              key: BONDY_REALM
        - name: PROVIDERS_SOURCE
          value: "benelux_providers.json"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
