apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../kind/base/cortex-iq-queries

namespace: macula-hub

# Patch Bondy URL and Database URL to point to beam-01 local services
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "ws://bondy.macula-platform.svc.cluster.local:18080/ws"
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "ecto://cortexiq:cortexiq123@postgres.macula-hub.svc.cluster.local:5432/cortexiq_dashboard"
    target:
      kind: Deployment
      name: cortex-iq-queries
