apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: macula-hub

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: macula-platform
      cluster: beam-01
