apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# nginx-ingress overlay for hub-01 cluster
# Patches the controller to publish LoadBalancer IP instead of localhost

namespace: ingress-nginx

resources:
  - ../../../base/nginx-ingress

patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - /nginx-ingress-controller
          - --election-id=ingress-nginx-leader
          - --controller-class=k8s.io/ingress-nginx
          - --ingress-class=nginx
          - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
          - --validating-webhook=:8443
          - --validating-webhook-certificate=/usr/local/certificates/cert
          - --validating-webhook-key=/usr/local/certificates/key
          - --watch-ingress-without-class=true
          - --publish-status-address=172.20.255.10
      - op: remove
        path: /spec/strategy/rollingUpdate
      - op: replace
        path: /spec/strategy/type
        value: Recreate
