apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-iq-homes
  namespace: macula-edge
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: homes
        env:
        - name: BONDY_URL
          valueFrom:
            configMapKeyRef:
              name: bondy-client-config
              key: BONDY_URL
        - name: BONDY_REALM
          valueFrom:
            configMapKeyRef:
              name: bondy-client-config
              key: BONDY_REALM
        - name: HOMES_SOURCES
          value: "brussels_homes_chunk_10.json,flanders_central_homes_chunk_10.json,flanders_east_homes_chunk_10.json,flanders_west_homes_chunk_10.json,wallonia_north_homes_chunk_10.json,wallonia_south_homes_chunk_10.json,netherlands_central_homes_chunk_10.json,netherlands_east_homes_chunk_10.json,netherlands_north_homes_chunk_10.json,netherlands_south_homes_chunk_10.json,netherlands_west_homes_chunk_10.json"
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
