---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: edge-01
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/gitops/kind/clusters/edge-01
  prune: true
  sourceRef:
    kind: GitRepository
    name: macula-gitops
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/gitops/kind/base/nginx-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: macula-gitops
  wait: true
  timeout: 5m0s
