---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: macula-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/competition
  url: ssh://git@github.com/macula-io/macula-energy-mesh-poc
  secretRef:
    name: flux-system
  ignore: |
    # Ignore everything except gitops directory
    /*
    !/infrastructure/
    /infrastructure/*
    !/infrastructure/gitops/
