---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: macula-hub
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/gitops/kind/hub
  prune: true
  sourceRef:
    kind: GitRepository
    name: macula-gitops
  targetNamespace: macula-hub
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bondy-console
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/gitops/kind/hub/bondy-console
  prune: true
  sourceRef:
    kind: GitRepository
    name: macula-gitops
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/gitops/kind/base/nginx-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: macula-gitops
  wait: true
  timeout: 5m0s
