apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cortex-iq-simulation
  - namespace.yaml
  - secrets.yaml

# Override namespace for hub cluster
namespace: macula-hub
