     STDIN
   1 ---
   2 apiVersion: v1
   3 kind: Secret
   4 metadata:
   5   name: bondy-credentials
   6   namespace: macula-hub
   7   labels:
   8     app: cortex-iq-simulation
   9 type: Opaque
  10 stringData:
  11   # Application user credentials for CortexIQ
  12   app-username: cortexiq
  13   app-password: macula-app-2025
