---
apiVersion: v1
kind: Secret
metadata:
  name: bondy-credentials
  namespace: macula-apps
  labels:
    app: cortex-iq-simulation
type: Opaque
stringData:
  # Application user credentials for CortexIQ
  app-username: cortexiq
  app-password: macula-app-2025
