apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cortex-iq-homes-macula-apikey.yaml
  - cortex-iq-utilities-macula-apikey.yaml
  - cortex-iq-dashboard-macula-apikey.yaml
