apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: macula-system

resources:
  - ../macula-os/namespace.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: cortexiq
  app.kubernetes.io/managed-by: flux
