---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bondy-console-config
  namespace: macula-system
  labels:
    app: bondy-console
    app.kubernetes.io/name: bondy-console
    app.kubernetes.io/component: web-console
data:
  settings.json: |
    {
      "bondyUrl": "ws://hub.macula.local/ws",
      "bondyHttpUrl": "http://hub.macula.local/admin",
      "defaultRealm": "com.leapsight.bondy",
      "defaultAuthMethod": "wampcra",
      "userKeysMax": 10,
      "keyMaxCharacters": 256
    }
