---
apiVersion: v1
kind: Service
metadata:
  name: bondy-console
  namespace: macula-platform
  labels:
    app: bondy-console
    app.kubernetes.io/name: bondy-console
    app.kubernetes.io/component: web-console
spec:
  type: ClusterIP
  selector:
    app: bondy-console
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
