import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :cortex_iq_dashboard_web, CortexIqDashboardWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "fG5p0/eLcFHZTe9A91yrlwAn1xal7VoXwQ+VnnlrTMwjoIx6iA8zfusceV0+WZqB",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:cortex_iq_dashboard_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:cortex_iq_dashboard_web, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :cortex_iq_dashboard_web, CortexIqDashboardWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/mesh_hub_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :cortex_iq_dashboard_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# WAMP / Bondy Configuration for local development
# These environment variables will be read by CortexIqDashboard.Application
# when starting the WAMP subscribers.
#
# To run the dashboard locally and connect to the cluster WAMP router:
# 1. The KinD cluster exposes Bondy via NodePort mappings:
#    - WAMP WebSocket: localhost:30080
#    - Admin API: localhost:30082
# 2. Set these environment variables before running `mix phx.server`:
#
#    export BONDY_URL="ws://localhost:30080/ws"
#    export BONDY_REALM="be.cortexiq.energy"
#    export BONDY_ADMIN_URL="http://localhost:30082"
#
# Or create a .env file and source it:
#    source .env
#
# The dashboard will connect to the cluster's Bondy instance and receive
# real-time events from homes/providers running in the cluster.
