apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller.yaml
  - rbac.yaml
  - ingress-class.yaml

labels:
  - pairs:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: macula-platform
