---
apiVersion: v1
kind: Secret
metadata:
  name: bondy-credentials
  namespace: macula-hub
  labels:
    app.kubernetes.io/part-of: macula-system
type: Opaque
stringData:
  # Application user credentials for CortexIQ
  app-username: cortexiq
  app-password: macula-app-2025

  # Realm URIs
  master-realm: com.leapsight.bondy
  app-realm: be.cortexiq.energy
