apiVersion: v1
kind: Service
metadata:
  name: bondy-mesh-cluster
  namespace: macula-edge
  labels:
    app: bondy-mesh
spec:
  type: LoadBalancer
  selector:
    app: bondy-mesh
  ports:
  - name: cluster
    port: 18086
    targetPort: 18086
    protocol: TCP
