apiVersion: v1
kind: Service
metadata:
  name: bondy-edge
  namespace: macula-system
  labels:
    app: bondy-edge
    app.kubernetes.io/name: bondy
    app.kubernetes.io/component: wamp-router-edge
spec:
  type: ClusterIP
  selector:
    app: bondy-edge
  ports:
  - name: http-ws
    port: 18080
    targetPort: 18080
    protocol: TCP
  - name: admin-api
    port: 18081
    targetPort: 18081
    protocol: TCP
