apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-iq-homes
  namespace: macula-apps
  labels:
    app: cortex-iq-homes
    app.kubernetes.io/name: cortex-iq-homes
    app.kubernetes.io/component: payload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-iq-homes
  template:
    metadata:
      labels:
        app: cortex-iq-homes
        app.kubernetes.io/name: cortex-iq-homes
        app.kubernetes.io/component: payload
    spec:
      containers:
      - name: homes
        image: macula/cortex-iq-homes:latest
        imagePullPolicy: Never
        env:
        - name: BONDY_URL
          value: "ws://172.20.0.2:30080/ws"
        - name: BONDY_REALM
          value: "be.cortexiq.energy"
        - name: NUM_HOMES
          value: "25"
        - name: HOME_ID_FILTER
          value: "all"  # Options: "all", "odd", "even"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
