#!/usr/bin/env bash

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} $*"
}

# Get Docker container IP for a KinD cluster control plane
get_cluster_ip() {
    local cluster=$1
    local container_name="${cluster}-control-plane"

    # Get IP from Docker inspect
    docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "${container_name}" 2>/dev/null || echo ""
}

# Collect cluster IPs and generate /etc/hosts entries
collect_and_generate() {
    log_step "Collecting cluster IPs from Docker containers..."
    echo

    # Get IPs for each cluster
    local hub_ip
    local edge01_ip
    local edge02_ip
    local edge03_ip
    local edge04_ip

    hub_ip=$(get_cluster_ip "macula-hub")
    edge01_ip=$(get_cluster_ip "macula-edge-01")
    edge02_ip=$(get_cluster_ip "macula-edge-02")
    edge03_ip=$(get_cluster_ip "macula-edge-03")
    edge04_ip=$(get_cluster_ip "macula-edge-04")

    # Validate all IPs were found
    if [[ -z "${hub_ip}" ]] || [[ -z "${edge01_ip}" ]] || [[ -z "${edge02_ip}" ]] || \
       [[ -z "${edge03_ip}" ]] || [[ -z "${edge04_ip}" ]]; then
        log_error "Failed to get IP addresses for all clusters"
        echo
        log_error "Hub:     ${hub_ip:-NOT FOUND}"
        log_error "Edge-01: ${edge01_ip:-NOT FOUND}"
        log_error "Edge-02: ${edge02_ip:-NOT FOUND}"
        log_error "Edge-03: ${edge03_ip:-NOT FOUND}"
        log_error "Edge-04: ${edge04_ip:-NOT FOUND}"
        echo
        log_error "Make sure all KinD clusters are running (kind get clusters)"
        return 1
    fi

    log_info "✓ Found cluster IPs:"
    echo "  Hub:     ${hub_ip}"
    echo "  Edge-01: ${edge01_ip}"
    echo "  Edge-02: ${edge02_ip}"
    echo "  Edge-03: ${edge03_ip}"
    echo "  Edge-04: ${edge04_ip}"
    echo

    # Generate hosts file entries
    cat <<EOF
# Macula Platform - KinD Cluster Ingress
# Generated by setup-hosts.sh on $(date)
${hub_ip}      hub.macula.local console.macula.local
${edge01_ip}   dashboard.cortexiq.local
${edge02_ip}   edge02.macula.local
${edge03_ip}   edge03.macula.local
${edge04_ip}   edge04.macula.local
EOF
}

# Update /etc/hosts file (must be running as root)
update_hosts_file() {
    local hosts_entries

    log_step "Generating /etc/hosts entries..."
    hosts_entries=$(collect_and_generate) || return 1

    echo
    log_info "Generated entries:"
    echo -e "${BLUE}${hosts_entries}${NC}"
    echo

    # Check if entries already exist
    if grep -q "# Macula Platform - KinD Cluster Ingress" /etc/hosts 2>/dev/null; then
        log_step "Removing old Macula Platform entries from /etc/hosts..."

        # Remove old entries (from marker to next empty line)
        sed -i.bak '/# Macula Platform - KinD Cluster Ingress/,/^$/d' /etc/hosts

        log_info "✓ Old entries removed (backup: /etc/hosts.bak)"
        echo
    fi

    log_step "Appending new entries to /etc/hosts..."

    # Append new entries
    echo "${hosts_entries}" >> /etc/hosts
    echo "" >> /etc/hosts  # Add blank line after

    log_info "✓ /etc/hosts updated successfully"
}

# Show entries and provide manual instructions
show_manual_instructions() {
    local hosts_entries

    log_step "Generating /etc/hosts entries..."
    hosts_entries=$(collect_and_generate) || return 1

    echo
    log_info "Generated entries to add to /etc/hosts:"
    echo
    echo -e "${BLUE}${hosts_entries}${NC}"
    echo

    log_warn "Not running as root - cannot update /etc/hosts automatically"
    echo
    echo -e "${CYAN}Option 1: Run with sudo${NC}"
    echo "  sudo $0"
    echo
    echo -e "${CYAN}Option 2: Manually add to /etc/hosts${NC}"
    echo "  Copy the entries above and add them to /etc/hosts using your editor:"
    echo "  sudo nano /etc/hosts"
    echo
    echo -e "${CYAN}Option 3: Append directly${NC}"
    echo "  cat <<'HOSTS_EOF' | sudo tee -a /etc/hosts"
    echo "${hosts_entries}"
    echo "  HOSTS_EOF"
    echo
}

main() {
    echo
    log_info "========================================"
    log_info "Setup /etc/hosts for Macula KinD clusters"
    log_info "========================================"
    echo

    # Check for required commands
    log_step "Checking prerequisites..."

    if ! command -v docker &> /dev/null; then
        log_error "docker command not found. Please install Docker."
        exit 1
    fi

    log_info "✓ Docker is available"
    echo

    # Check if running as root
    if [[ $EUID -eq 0 ]]; then
        log_info "Running as root - will update /etc/hosts directly"
        echo

        update_hosts_file || exit 1

        echo
        log_info "========================================"
        log_info "✓ /etc/hosts setup complete!"
        log_info "========================================"
        echo
        log_info "You can now access services via:"
        echo "  • http://hub.macula.local:8080/         (Bondy API Gateway)"
        echo "  • http://hub.macula.local:8080/admin/   (Bondy Admin API)"
        echo "  • http://console.macula.local:8080/     (Bondy Web Console)"
        echo "  • http://dashboard.cortexiq.local:8080/ (CortexIQ Dashboard)"
        echo
        log_info "Note: nginx-ingress uses ports 8080 (HTTP) and 8443 (HTTPS)"
        echo
    else
        log_info "Not running as root - showing manual instructions"
        echo

        show_manual_instructions
    fi
}

main "$@"
