apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Edge-03: Homes with odd IDs (1, 3, 5, 7, ... 49)

resources:
  - namespace.yaml
  - ../../base/cortex-iq-homes

patches:
  - target:
      kind: Deployment
      name: cortex-iq-homes
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "odd"
